#ifndef ADJUSTTHRESHOLD_GLOBAL_H
#define ADJUSTTHRESHOLD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ADJUSTTHRESHOLD_LIBRARY)
#  define ADJUSTTHRESHOLD_EXPORT Q_DECL_EXPORT
#else
#  define ADJUSTTHRESHOLD_EXPORT Q_DECL_IMPORT
#endif

#endif // ADJUSTTHRESHOLD_GLOBAL_H
